name: Pull request 

# on: pull_request  
on:
  push:
    branches:
      - feat-codecov

jobs:
  lint_test_build:
    name: lint, test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
            
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: npm install
        run: npm install
      
      - name: lint
        run: npm run lint

      - name: test
        run: npm run test
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: build
        run: npm run build

      - name: build storybook
        run: npm run build-storybook
